### ISSUE TITLE
Enhancement: RISmed

### ISSUE THREAD

**Issue by halterc** [NMikolajewicz/scPipeline#2]
Hi Nicholas,

Congratulation on your Nature publication. And tank you very much for your cool tool. I's very useful and might make scRNA-seq exploratory data analysis a lot more convenient...it's awesome :)

One point: along the way, finding and installing the required packages is not very convenient but.

Especially one required package for the 
M06_GeneExpressionAssociation_public.Rmd
is not very obvious and easy to miss, as it is called in a "try" statement and doesn't raise an obvious "hey, please install library RISmed" flag but gives a rather cryptic error "Error in convertIdx" a bit further down.

-> solution: I would include it in the packages2load right at the top

Thanks again and looking forward to advance your cool pipeline! :)

Best,
Chris

**Comment by halterc** [comment]
Implemented

**Comment by NMikolajewicz** [comment]
Thank you!
