### ISSUE TITLE
Resquest for help

### ISSUE THREAD

**Issue by Rainjie-afk** [NMikolajewicz/scPipeline#6]
Hello Nicholas, I successfully installed the scPipeline. Thank you for developing such a useful tool!

But as a slow learner, I have a question to ask you. Despite reading the tutorials many times, I can't find a solution to resolve this problem
For example, I have 6 samples, 2 experimental groups, and each group has 3 Biological replicates;
So, I use 'M02_DataIntegration_public_v2.Rmd' integration all 6 samples in one '.Rdata'.
How should I do downstream analysis in two groups? 
eg. In SeuratData(ifnb) I can use the command line `ifnb.list <- SplitObject(ifnb, split.by = "stim")` to divide into groups ('ctrl' and 'stim')

Yujie

**Comment by Rainjie-afk** [comment]
I'm sorry but i think i solve this problem.

**Comment by Rainjie-afk** [comment]
I'm so sorry but I have to reopen this issue. 
when I finish 'M02_DataIntegration.rmd' by integrating 'barcode'.
How should I do downstream analysis in two groups? Because I have found M03 cluster all groups on one.
![下载](https://user-images.githubusercontent.com/68232446/230002013-ae107997-eda8-4d27-9892-c4c5f827f4ff.png)
![下载 (1)](https://user-images.githubusercontent.com/68232446/230002097-73f59212-716f-4b6c-aa7e-b1edf72be63d.png)


Also,I add integrate.by = "Barcode" in parameter.list ,but still don't work.

Many thanks 

Yujie

**Comment by NMikolajewicz** [comment]
The current scPipeline is not designed for pairwise comparison of different conditions, however the preprocessing and integration that you've performed in scPipeline gives you a seurat object that you can then use for these downstream analyses. 

The downstream analysis will depend entirely on what your question is. If you're interested in identifying differentially expressed genes among a specific cell type, you can filter out that specific cluster and run differential expression analyses using tools like getDEGs(...) or findCDImarkers(...) in the scMiko R package (https://github.com/NMikolajewicz/scMiko). Alternatively you can also look at differential abundance between various conditions using the miloR package (https://marionilab.github.io/miloR/articles/milo_demo.html).

**Comment by Rainjie-afk** [comment]
> 

Many thanks for your reply and your awesome scPipeline, it really helps me a lot!
Yujie

**Comment by Rainjie-afk** [comment]
> The current scPipeline is not designed for pairwise comparison of different conditions, however the preprocessing and integration that you've performed in scPipeline gives you a seurat object that you can then use for these downstream analyses.
> 
> The downstream analysis will depend entirely on what your question is. If you're interested in identifying differentially expressed genes among a specific cell type, you can filter out that specific cluster and run differential expression analyses using tools like getDEGs(...) or findCDImarkers(...) in the scMiko R package (https://github.com/NMikolajewicz/scMiko). Alternatively you can also look at differential abundance between various conditions using the miloR package (https://marionilab.github.io/miloR/articles/milo_demo.html).

**Comment by Rainjie-afk** [comment]
Sorry to open this issue again. But I meet another problem in 'M04_CellAnnotation_public'.
**Everything went smoothl**y when I use the default settings,but this goes wrong when I try to annotation cell type with customer database, here is my example: 
`external.markers = list (B_cell_land = c("Ebf1","Cd79a","Cd79b","Cd79b","Ly6d","Ighm","Ms4a1"), Cholangiocyte_land = c("Clu","Spp1","Tm4sf4","Cp","Ambp","Krt18")), `
`internal.markers= NULL,` 
`marker.filter = NULL,`

Here is error message : 

> List of 3

>  $ include   : logi FALSE

 > $ fig.width : num 12
 > $ fig.height: num 5

 >  |..................                                                    |  26%
 > ordinary text without R code

  > |...................                                                   |  28%

> label: score calculation
> Quitting from lines 390-449 (M04_CellAnnotation_public_res_0.5_custmor_annotation.Rmd) 
> Error in `[.data.frame`(object@meta.data, , paste0("cluster_", names(geneset))) : 
> Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> sigScore -> [ -> [.data.frame`

![image](https://user-images.githubusercontent.com/68232446/232194273-fbe00d0c-74f1-45eb-992d-3ee82e698c4b.png)

After Rename `external.markers`, things went smoothly.
Thanks again !

**Comment by Rainjie-afk** [comment]
I'm sorry to ask another question, but this one is quite important to me.
After run " M02_DataIntegration_public_v2", I had found that `str(so@assays$integrated@counts)` was missing.
I realized that `so@assays$integrated@counts` is essential for downstream analysis, especially in MiloR (You recommended me to do differential abundance between various conditions).
So, Here is my question , How can I keep `so@assays$integrated@counts` after run " M02_DataIntegration_public_v2" ?
![image](https://user-images.githubusercontent.com/68232446/232315531-8a41dc85-38b7-466a-8817-09180e851629.png)

Sincerely yours 
Yujie

**Comment by NMikolajewicz** [comment]
The data integration step does not integrate counts. You will need to use counts from the "RNA" or "SCT" assay for MiloR. MiloR may also have some tutorials or suggestions in their documentation how to handle integrated data, so be sure check that out.

**Comment by Rainjie-afk** [comment]
> The data integration step does not integrate counts. You will need to use counts from the "RNA" or "SCT" assay for MiloR. MiloR may also have some tutorials or suggestions in their documentation how to handle integrated data, so be sure check that out.

Many thanks for your reply! I will try!
